apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: web-sgl
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          custom: "true"
  template:
    metadata:
      name: 'web-sgl-production'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/wintech-thai/nap-k3s-server-002.git
        targetRevision: "production" #Based on environment
        path: '99-deployments/manifests/web-sgl'
      destination:
        name: in-cluster
        namespace: web-sgl
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
