apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: web-youngyou
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          custom: "true"
  template:
    metadata:
      name: 'web-youngyou-{{name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/wintech-thai/nap-k3s-server-002.git
        targetRevision: "{{name}}" #Based on environment
        path: '99-deployments/manifests/web-youngyou'
      destination:
        name: in-cluster
        namespace: web-youngyou
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
