---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wordpress-user-login
spec:
  refreshInterval: 1h          # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store     # name of the SecretStore (or kind specified)
  target:
    name: wordpress-user-login  # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: "wordpress-password"
      remoteRef:
        key: initial-secret-preset
        property: WP_ADMIN_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wordpress-db-login
spec:
  refreshInterval: 1h          # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store     # name of the SecretStore (or kind specified)
  target:
    name: wordpress-db-login  # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: "mysql-root-password" # For MySQL
      remoteRef:
        key: initial-secret
        property: POSTGRES_PASSWORD

    - secretKey: "mysql-password" # For MySQL
      remoteRef:
        key: initial-secret
        property: POSTGRES_PASSWORD

    - secretKey: "mariadb-password" # For Wordpress
      remoteRef:
        key: initial-secret
        property: POSTGRES_PASSWORD
